import { ProviderType } from "@/ai/types";
import { RoutingTier, type ProviderCapabilityProfile } from "@/router/types";

export const providerCapabilityProfiles: readonly ProviderCapabilityProfile[] =
  [
    {
      provider: ProviderType.Groq,
      displayName: "Groq",
      defaultModel: "llama-3.1-8b-instant",
      supportsStreaming: true,
      supportsJson: true,
      supportsTools: false,
      supportsReasoning: false,
      supportsVision: false,
      supportsStructuredOutput: true,
      supportsMultimodal: false,
      contextWindowTokens: 8_192,
      maxOutputTokens: 2_048,
      costTier: RoutingTier.Low,
      latencyTier: RoutingTier.Low,
      qualityTier: RoutingTier.Medium,
      reliabilityScore: 0.82,
      strengths: ["fast", "low-cost", "chat", "summarization"],
    },
    {
      provider: ProviderType.Mistral,
      displayName: "Mistral",
      defaultModel: "mistral-small-latest",
      supportsStreaming: true,
      supportsJson: true,
      supportsTools: false,
      supportsReasoning: true,
      supportsVision: false,
      supportsStructuredOutput: true,
      supportsMultimodal: false,
      contextWindowTokens: 32_000,
      maxOutputTokens: 4_096,
      costTier: RoutingTier.Low,
      latencyTier: RoutingTier.Medium,
      qualityTier: RoutingTier.Medium,
      reliabilityScore: 0.84,
      strengths: ["balanced", "writing", "translation", "analysis"],
    },
    {
      provider: ProviderType.Gemini,
      displayName: "Gemini",
      defaultModel: "gemini-1.5-flash",
      supportsStreaming: true,
      supportsJson: true,
      supportsTools: false,
      supportsReasoning: true,
      supportsVision: true,
      supportsStructuredOutput: true,
      supportsMultimodal: true,
      contextWindowTokens: 1_000_000,
      maxOutputTokens: 8_192,
      costTier: RoutingTier.Medium,
      latencyTier: RoutingTier.Medium,
      qualityTier: RoutingTier.High,
      reliabilityScore: 0.8,
      strengths: ["long-context", "research", "vision", "multimodal"],
    },
    {
      provider: ProviderType.OpenAI,
      displayName: "OpenAI",
      defaultModel: "gpt-4o-mini",
      supportsStreaming: true,
      supportsJson: true,
      supportsTools: true,
      supportsReasoning: true,
      supportsVision: true,
      supportsStructuredOutput: true,
      supportsMultimodal: true,
      contextWindowTokens: 128_000,
      maxOutputTokens: 16_384,
      costTier: RoutingTier.Medium,
      latencyTier: RoutingTier.Medium,
      qualityTier: RoutingTier.High,
      reliabilityScore: 0.88,
      strengths: ["quality", "structured-output", "coding", "tools-ready"],
    },
    {
      provider: ProviderType.Claude,
      displayName: "Claude",
      defaultModel: "claude-3-5-sonnet-latest",
      supportsStreaming: true,
      supportsJson: false,
      supportsTools: true,
      supportsReasoning: true,
      supportsVision: true,
      supportsStructuredOutput: false,
      supportsMultimodal: true,
      contextWindowTokens: 200_000,
      maxOutputTokens: 8_192,
      costTier: RoutingTier.High,
      latencyTier: RoutingTier.Medium,
      qualityTier: RoutingTier.High,
      reliabilityScore: 0.86,
      strengths: ["reasoning", "analysis", "writing", "long-context"],
    },
  ];
